<a href="https://colab.research.google.com/github/mrmids/fma-predictions/blob/Python-Code-Dev/Final_Project_TeamFMA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# [`IT Experience November Python: Final Project`](https://github.com/mrmids/fma-predictions "Project GitHub Repository")

_Collaborators: Midowa Gbededo & Lucky Omenihu_

### **Project Overview**
[`IT Experience`](https://itexperience.org/ "IT Experience Website") organized a free Python class in November, 2020 and as part of the class completion a final project was assigned. Teams were encouraged to work on open source machine learning datasets.

Our team - "TEAM-FMA", chose to work on the [`Free Music Archive (FMA) dataset`](https://github.com/mdeff/fma "FMA Github Repository") which is a dataset for [`Music Information Retrieval (MIR)`](https://musicinformationretrieval.com/why_mir.html "About MIR") and digital music analysis.

This dataset has been analyzed by the original creators of the idea and there exists ample information on analyzing this dataset on their Github repository. 

_Many of the comments in this notebook are quotations lifted directly from the information page of the original FMA team. All such comments will be recognized with traditional quotation marks " "_

For more information about the original FMA project, please consult:
1. [`FMA's academic paper`](https://arxiv.org/abs/1612.01840 "Paper")
2. [`FMA's UCI Machine Learning Repository`](https://archive.ics.uci.edu/ml/datasets/FMA%3A+A+Dataset+For+Music+Analysis "UCI Repository")

##### **Data Analysis Workflow**
Our team chose to implent the [`CRoss Industry Standard Process for Data Mining (CRISP-DM)`](https://en.wikipedia.org/wiki/Cross-industry_standard_process_for_data_mining "CRISP-DM Wikipedia Page") methodology for our analysis.

"CRSIP-DM describes the data-mining process in six steps": [`(citation: Abbott, D, "Applied Predictive Analytics - Principles and Techniques for the Professional Data Analyst", pp 19-21, Wiley - 2014)`](https://www.wiley.com/en-us/Applied+Predictive+Analytics%3A+Principles+and+Techniques+for+the+Professional+Data+Analyst-p-9781118727966 "Wiley Publishers - Book Link") 

|STAGE   |DESCRIPTION|
|:------|:----------|
|1. Business Understanding| Define the project|
|2. Data Understanding| Examine the data; identify problems in the data|
|3. Data Preparation| Fix problems in the data; create derived variables|
|4. Modeling| Build predictive or descriptive models|
|5. Evaluation| Assess models; report on the expected effects of models
|6. Deployment| Plan for use of models|

What now follows is implementation of the CRISP-DM workflow through the use of the FMA dataset.
*****

### **1 - Business Understanding**
The idea behind this dataset is an effort to utilize machine learning to complete tasks of sorting and organizing large collections of digital music - MP3 files. Some reasons to use machine learning in this way, to name a few, include:

- Sorting large collections of digital music files into genre automatically
- Identifying the sonic signatures of popular music in different genres
- Cover song detection, i.e. what songs were produced by sampling other songs? and for given a cover song, identify what song was sampled
- Recognize the instruments used in songs

Commercial applications of MIR include:
- Software that teach musical instrument playing, by converting digital music files into easy to play music chords. [`Example - Chordify`](https://chordify.net/ "Chordify")
- Software to auto-tune music samples during music production. [`Example - Melodyne`](https://www.celemony.com/en/start "Melodyne")
- Software to detect musical key of audio samples aiding digital music production. [`Example - iZotope Nectar`](https://www.izotope.com/en/products/nectar.html "iZotope Nectar")
- Apps that identify and name any song playing around you. [`Example - Shazam`](https://www.shazam.com/ "Shazam")


Refer to the [`MIR Documentation`](https://musicinformationretrieval.com/why_mir.html "About MIR") for more information on MIR and it's uses.

*****

### **Python Packages Used:**
- [`Librosa:`](https://librosa.org/ "Librosa") audio and music processing in python
- [`Google-Colab:`](https://pypi.org/project/google-colab/ "Google-Colab") colaboratory-specific python libraries
- [`Pandas:`](https://pandas.pydata.org/ "Pandas") data analysis and manipulation tool
- [`NumPy:`](https://numpy.org/ "NumPy") scientific computing with Python
- [`Matplotlib:`](https://matplotlib.org/ "Matplotlib") comprehensive library for creating static, animated, and interactive visualizations in Python
- [`Seaborn:`](https://seaborn.pydata.org/ "Seaborn") provides a high-level interface for drawing attractive and informative statistical graphics
- [`SciKit Learn:`](https://scikit-learn.org/stable/ "SKLearn") machine Learning in Python
- [`Keras:`](https://keras.io/ "Keras") high-level neural networks API for Python
- [`IPython:`](https://ipython.org/ "IPython") provides a rich architecture for interactive computing
- [`CSV:`](https://docs.python.org/3/library/csv.html "CSV") module implements classes to read and write tabular data in CSV format [(useful examples)](https://www.programiz.com/python-programming/reading-csv-files)
- [`Warnings:`](https://docs.python.org/3/library/warnings.html "Warnings") provides control of warning message output on notebook screen
- [`AST:`](https://docs.python.org/3/library/ast.html "Abstract Syntax Trees") helps Python applications to process trees of the Python abstract syntax grammar [(more info here)](https://www.mattlayman.com/blog/2018/decipher-python-ast/)
- [`Folium:`](https://pypi.org/project/folium/ "Folium") Manipulate your data in Python, then visualize it in a Leaflet map
- [`GeoPandas:`](https://geopandas.org/index.html "GeoPandas") make working with geospatial data in python easier
- [`EarthPy:`](https://pypi.org/project/earthpy/ "EarthPy") EarthPy makes it easier to plot and manipulate spatial data in Python
- [`Shapely`](https://shapely.readthedocs.io/en/latest/manual.html#introduction "Shapely") a Python package for set-theoretic analysis and manipulation of planar features

*****

### **Useful Solution Links For Challenges Ecountered:**

1. _Read CSV file into Colab from Google Drive folder:_ Utilized the drive mount method in the Google-Colab package. [`Loading data into Colab from Google Drive`](https://towardsdatascience.com/3-ways-to-load-csv-files-into-colab-7c14fcbdcb92 "CSV from Google Drive")
2. *Read CSV file with multi-row headers using `pandas.read_csv`:* First solved the multi row header challenge here [`Pandas DataFrame: Playing with CSV files`](https://towardsdatascience.com/pandas-dataframe-playing-with-csv-files-944225d19ff "CSV Multi-Row Header"), then tackled renaming rows and column that showed up as "unnamed" using the tips from [`Stack Overflow`](https://stackoverflow.com/questions/48059994/mark-empty-values-in-pandas-dataframe-multi-row-header "Rename dataframe columns"). A sample from the data developers showing what the proper csv file read should look like is seen in this [`screenshot example`](https://ibb.co/DtWXXqX "screenshot")
3. *Force index of pandas dataframe to be the first column of the CSV file using `pandas.DataFrame.set_index`:* The first resource found for this problem was to use the [`Pandas Set Index`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.set_index.html "Pandas Set Index"). Some more help from [`Stackoverflow`](https://stackoverflow.com/questions/38542419/could-pandas-use-column-as-index "Stackoverflow Index")
4. _Hierarchical indexing of pandas dataframe:_ Resource found for this problem was to use the [`Pandas Hierarchical indexing`](https://pandas.pydata.org/pandas-docs/stable/user_guide/advanced.html "Pandas Hierarchical indexing"). Ended up going with the suggestions from the class mentors - Vishal and Michael
5. *Plotting latitude and longitude points on map:* [`Method 1 - Use Shape Files`](https://towardsdatascience.com/geopandas-101-plot-any-data-with-a-latitude-and-longitude-on-a-map-98e01944b972 "GeoPandas 101"), too static. [`Method 2 - Use Image File`](https://towardsdatascience.com/easy-steps-to-plot-geographic-data-on-a-map-python-11217859a2db "Image as Map") still too static. [`Method 3 - Interactive Folium Maps`](https://www.earthdatascience.org/courses/scientists-guide-to-plotting-data-in-python/plot-spatial-data/customize-vector-plots/interactive-leaflet-maps-in-python-folium/ "Folium") this is a good option, but there's more interactive options. [`Method 4 - Interactive IpyLeaflet Maps`](https://towardsdatascience.com/ipyleaflet-interactive-mapping-in-jupyter-notebook-994f19611e79 "IpyLeaflet") lots of functionality, slightly more complicated steps. [`Method 5 - Jupyter Blog - Interactive Maps`](https://blog.jupyter.org/interactive-gis-in-jupyter-with-ipyleaflet-52f9657fa7a "Jupyter Blog IpyLeaflet") This tutorial is the best seen so far, tried it, but Colab doesn't support IpyLeaflet. [`Method 6 - Geographic Data with Basemap`](https://colab.research.google.com/github/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/04.13-Geographic-Data-With-Basemap.ipynb?authuser=1#scrollTo=_Mgwp62zuJL2 "Colab maps with mpl_toolkits") this method looks promising, although the maps are not interactive, the tutorial is useful. [`Method 7 - Google Earth Engine`](https://developers.google.com/earth-engine/guides/python_install-colab "Google Earth Engine") this one requires authentication from Google. [`Method 8 - Iteration with Folium`](https://github.com/collinreinking/longitude_latitude_dot_plots_in_python_with_folium "Iterative Markers"). This is a step by step easy to follow method. [`Bonus Method`](https://stackoverflow.com/questions/39401729/plot-latitude-longitude-points-from-dataframe-on-folium-map-ipython "Bonus Solution")
6. *Count occurence of words in Pandas column:* [`Count Occurrence in Column`](https://www.marsja.se/pandas-count-occurrences-in-column-unique-values/#:~:text=How%20do%20you%20Count%20the,in%20the%20column%20%E2%80%9Ccondition%E2%80%9D. ".value_counts")
7. *Better control of Folium map boundary:* [`Solution: Set Folium figure first`](https://stackoverflow.com/questions/48789751/set-map-boundary-and-stop-endless-panning-in-a-loop-of-folium-map "Stackoverflow Folium Size")
8. *Convert Lat-Long points to Country:* [`python library countries`](https://github.com/che0/countries "countries.py") ran into trouble with this library, one of the sub packages wasn't calling properly. [`GeoPy`](https://pypi.org/project/geopy/ "GeoPy package") seems promising, looks like it needs OSM app installation. [`Google GeoAPI`](https://stackoverflow.com/questions/20169467/how-to-convert-from-longitude-and-latitude-to-country-or-city "Google GeoAPI")
9. *Drop NAN values from DataFrame:* [`Drop NAN`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.notna.html "Not NA"). Then set collected indicies to specified values [`Set Row by Index`](https://stackoverflow.com/questions/13842088/set-value-for-particular-cell-in-pandas-dataframe-using-index "Set Row by Index")

*****

In [1]:
## Connect to Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
## Install libraries not already available in virtual machine.
# The code below is commented out to prevent unnecessary installation everytime.

#!pip install geopandas
#!pip install earthpy
#!pip install ipyleaflet

#!apt-get install libgeos-3.5.0
#!apt-get install libgeos-dev
#!pip install https://github.com/matplotlib/basemap/archive/master.zip
#!pip install pyproj==1.9.6

#!pip install countries

In [1]:
## Import the necessary library packages

%matplotlib inline

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn as skl
import sklearn.utils, sklearn.preprocessing, sklearn.decomposition, sklearn.svm
import librosa
import librosa.display
import os
import IPython.display as ipd
import csv
import ast
import folium
import geopandas as gpd
import earthpy as et
from shapely.geometry import Point
from mpl_toolkits.basemap import Basemap
import ee
import math
from IPython.display import Image
import countries
from geopy.geocoders import Nominatim

import urllib
import json

import warnings
warnings.filterwarnings('ignore')
#warnings.filterwarnings(action='once')

In [ ]:
# Trigger the authentication flow.
ee.Authenticate()

# Initialize the library.
ee.Initialize()

In [3]:
# Defining function to read FMA metadata with multi-row headers and use first column as index
#**This step contains some data preparation in form of manipulating the multi-row header**

def load_metadata(filepath):

  '''
  This function takes in the filepath for one of the CSV metadata files for the FMA dataset
  and loads the CSV into a Pandas DataFrame with the proper indexing and multi-level headers
  
  Input: filepath = metadata folder location for the CSV file

  Output: Depending on the conditional statements, one of the datasets in the metadata
          folder properly formatted for multi-level headers, first column as index column,
          and for the tracks dataset, enable processing of abstract syntax trees (ASTs) typically data with Python expressions,
          conversion of date and time columns to their proper format,
          converting the subset column into ordered categories and declaring categorical columns

  Modified by TeamFMA 12/11/2020
  '''
  # Extract the final component of a pathname 
  filename = os.path.basename(filepath)
  
  # Conditional statements since each dataset has different header row counts and tracks needs special treatment  
  if 'features' in filename:
      return pd.read_csv(filepath, index_col=0, header=[0, 1, 2])
  if 'echonest' in filename:
      return pd.read_csv(filepath, index_col=0, header=[0, 1, 2])
  if 'genres' in filename:
      return pd.read_csv(filepath, index_col=0)
    
  if 'tracks' in filename:
    tracks = pd.read_csv(filepath, index_col=0, header=[0, 1])
  
    # Process columns in tracks dataset that have AST
    COLUMNS = [('track', 'tags'), ('album', 'tags'), ('artist', 'tags'),
                ('track', 'genres'), ('track', 'genres_all')]
    for column in COLUMNS:
      tracks[column] = tracks[column].map(ast.literal_eval)
        
    # Covert date and time columns to proper pandas datetime format
    COLUMNS = [('track', 'date_created'), ('track', 'date_recorded'),
                ('album', 'date_created'), ('album', 'date_released'),
                ('artist', 'date_created'), ('artist', 'active_year_begin'),
                ('artist', 'active_year_end')]
    for column in COLUMNS:
      tracks[column] = pd.to_datetime(tracks[column])
        
    # Order the column with the music sampling subsets
    SUBSETS = ('small', 'medium', 'large')
    tracks['set', 'subset'] = tracks['set', 'subset'].astype(
        pd.CategoricalDtype(categories=SUBSETS, ordered=True))
        
    # Set datatype for categorical columns appropriately
    COLUMNS = [('track', 'genre_top'), ('track', 'license'),
                ('album', 'type'), ('album', 'information'),
                   ('artist', 'bio')]
    for column in COLUMNS:
        tracks[column] = tracks[column].astype('category')
        
    return tracks

In [4]:
## Identify folder holding mp3 files ** Change path to how it appears on your google drive

path_audio_dir = "/content/drive/MyDrive/Colab Notebooks/ITExperience Python Training/Final Project/fma_small"

audio_dir = os.environ.get(path_audio_dir)

In [5]:
## Load the url paths from Google Drive for the FMA MetaData Data Files ** Change path to how it appears on your google drive

path_metadata = "/content/drive/MyDrive/Colab Notebooks/ITExperience Python Training/Final Project/fma_metadata"

path_echonest = path_metadata + "/echonest.csv"
path_tracks = path_metadata + "/tracks.csv"
path_features = path_metadata + "/features.csv"
path_genres = path_metadata + "/genres.csv"

In [70]:
# Load metadata and features.
genres = load_metadata(path_genres)
features = load_metadata(path_features)
echonest = load_metadata(path_echonest)
tracks = load_metadata(path_tracks)

In [ ]:
# "The Echonest file contains audio features provided by Echonest for a subset of 13,129 tracks"
# "Tracks data contains per track metadata such as ID, title, artist, genres, tags and play counts, for all 106,574 tracks"
# "Features data contains per track common features extracted with librosa, for all 106,574 tracks"
# "Genre data contains all 163 genres with name and parent (used to infer the genre hierarchy and top-level genres)"


*****
### **2 - Data Understanding**

Three of the four CSV files contained in the fma_metadata folder have multi-row headers. This means that the dataframes can be referenced at multiple levels and each dataframe can be sliced up in smaller sub-sections for analysis.

Dataframe column levels and column name lists are used to inspect the dataframes. Sample code used to do this is as follows:

    #To check the column levels
    echonest.columns.levels

    #To check the column names
    list(echonest.columns.values.tolist())

##### **2.1 - Check For Data Consitency**

Check that the row counts and relational key between tables, in our case the "track_id" column, are all consistent and that the size of the data splits from the FMA project


In [7]:
# Checking for data consistency using assert condition
# Conditions that need to be satisfied are:
# 1. Features dataframe needs to be the sasme size as the tracks dataframe. 
#     The features dataframe represent sonic signatures extracted from every song in the track folder
#     The tracks dataframe
# 2. The track IDs  in the echonest dataset are also contained in the tracks and features files
# assert works by not returning any errors. If false, then there is an error

np.testing.assert_array_equal(features.index, tracks.index)
assert echonest.index.isin(tracks.index).all()

In [8]:
# Inspect shape of data files loaded 
tracks.shape, genres.shape, features.shape, echonest.shape

((106574, 52), (163, 4), (106574, 518), (13129, 249))

##### **2.2 - The Tracks Dataset**

"Tracks data contains per track metadata such as ID, title, artist, genres, tags and play counts, for all 106,574 tracks"

Using basic print and dataframe functions to inspect the tracks dataset, it is 

In [9]:
# Quick view of what's contained in the Tracks dataset

tracks.head()

album                      ... track                 
         comments        date_created  ...  tags            title
track_id                               ...                       
2               0 2008-11-26 01:44:45  ...    []             Food
3               0 2008-11-26 01:44:45  ...    []     Electric Ave
5               0 2008-11-26 01:44:45  ...    []       This World
10              0 2008-11-26 01:45:08  ...    []          Freeway
20              0 2008-11-26 01:45:05  ...    []  Spiritual Level

[5 rows x 52 columns]

In [10]:
# Check for size of the data split subsets

for subset in tracks['set', 'subset'].unique():
    indicator = tracks['set', 'subset'] <= subset
    print('{:6} {:6} tracks  {:.1f} days'.format(
        subset, sum(indicator), sum(indicator) * 30 / 3600 / 24))

small    8000 tracks  2.8 days
medium  25000 tracks  8.7 days
large  106574 tracks  37.0 days


In [11]:
# Summary of the Tracks dataset

print('{} tracks, {} artists, {} albums, {} genres'.format(
    len(tracks), len(tracks['artist', 'id'].unique()),
    len(tracks['album', 'id'].unique()),
    sum(genres['#tracks'] > 0)))
mean_duration = tracks['track', 'duration'].mean()
print('Tracks duration: {:.0f} days total, {:.0f} seconds average'.format(
    sum(tracks['track', 'duration']) / 3600 / 24,
    mean_duration))

106574 tracks, 16341 artists, 14854 albums, 161 genres
Tracks duration: 343 days total, 278 seconds average


In [14]:
### Comment block of useful geo plotting code

## This block creats points with combination Lat Longs and adds as a column in DF
#crs = {'init': 'epsg:4326'}
#geo_points = [Point(xy) for xy in zip(tracks['artist','longitude'],tracks['artist','latitude'])]
#geo_points[:3]
#tracks = gpd.GeoDataFrame(tracks, crs = crs, geometry = geo_points)

## This block gets the extreme boundaries of the artist locations
#MapBoundaries = (tracks['artist','longitude'].min(),   tracks['artist','longitude'].max(),      
#         tracks['artist','latitude'].min(), tracks['artist','latitude'].max())

#MapBoundaries


In [12]:
# Understanding what countries the artists are located in, using latitude and longitude data

map_figure = folium.Figure(width=1000, height=500) #fix the figure size on which map is drawn

# Extract rows for which there is available location data, skip NANs
lats = tracks['artist','latitude'].dropna().tolist()
longs = tracks['artist','longitude'].dropna().tolist()

# Draw the basemap
tracks_map = folium.Map(prefer_canvas=True, width=1000,height=500,zoom_start=4).add_to(map_figure)

# Loop through each available latitude and longitude, add a dot to map for each location
for i in range(len(lats)):
  folium.CircleMarker(location=[lats[i], longs[i]], radius=1).add_to(tracks_map)

 ##### **Getting Counts of Countries in Tracks**
 This method worked except the free account gives only limited reverse lookups per day. Candidate for coding in a pause maybe?   
    #geolocator = Nominatim(user_agent="TeamFMA")
    #tracks['artist','address'] = np.nan
    #tracks['artist','country'] = np.nan
    #for indx in tracks[tracks['artist','latitude'].notna()].index.tolist():
    #tracks['artist','address'][indx] = geolocator.reverse(tracks['artist','latitude'][indx], tracks['artist','longitude'][indx])
    #temp = str(tracks['artist','address'][indx]).split(',')
    #tracks['artist','country'][indx] = temp[-1]

##### **Geographic Locations of Artists**

Majority of the digital files in the dataset are from artists in the Unites States and Western Europe.

![Artist Locations](https://drive.google.com/uc?id=1Cg82XGLNZ9fFezeQJs_4XjVo47fqO92U)

##### **Understanding the Sections of the Tracks Dataset**

The tracks dataset is compesed of 4 main sections:
- track metadata
- album information
- artist information
- set tag, which is suggested split of data into training-testing-validation for ML

The tracks are also subsetted into splits of small, medium and large for analysis of the audio files. Since the audio datasets are quite large (the largest being over 700 GB), this project's audio file analysis focuses on the small subset.

In [98]:
# Display the top portion of each section of the tracks data

ipd.display(tracks['track'].head())
ipd.display(tracks['album'].head())
ipd.display(tracks['artist'].head())
ipd.display(tracks['set'].head())

bit_rate  comments   composer  ... publisher tags            title
track_id                                 ...                                
2           256000         0        NaN  ...       NaN   []             Food
3           256000         0        NaN  ...       NaN   []     Electric Ave
5           256000         0        NaN  ...       NaN   []       This World
10          192000         0  Kurt Vile  ...       NaN   []          Freeway
20          256000         0        NaN  ...       NaN   []  Spiritual Level

[5 rows x 20 columns]

comments        date_created  ... tracks   type
track_id                                ...              
2                0 2008-11-26 01:44:45  ...      7  Album
3                0 2008-11-26 01:44:45  ...      7  Album
5                0 2008-11-26 01:44:45  ...      7  Album
10               0 2008-11-26 01:45:08  ...      2  Album
20               0 2008-11-26 01:45:05  ...     13  Album

[5 rows x 13 columns]

active_year_begin  ... country
track_id                    ...        
2               2006-01-01  ...     NaN
3               2006-01-01  ...     NaN
5               2006-01-01  ...     NaN
10                     NaT  ...     NaN
20              1990-01-01  ...     NaN

[5 rows x 19 columns]

split  subset
track_id                  
2         training   small
3         training  medium
5         training   small
10        training   small
20        training   large

##### **2.3 - The Echonest Dataset**

"The Echonest file contains audio features provided by Echonest for a subset of 13,129 tracks"

Utilize basic print and dataframe functions to inspect what is inside the Echonest dataset.

It is seen that the Echonest dataset is comprised of the following multi-level hierrarchy for **each track**:

1. _Audio features:_ acousticness, danceability, energy, liveliness, tempo etc.
2. _Track Metadata:_ album name, date, artist, artist geographic location etc.
3. _Track Music Charts Ranking:_ artist popularity, familiarity, song hotness etc.
4. _Track Social Features:_ measures of artist based on social parameters - artist hotness
5. _Temporal Features:_ Represents 223 different properties used to classify each track

In [99]:
echonest.head()

echonest                         ...                                         
         audio_features                         ... temporal_features                       
           acousticness danceability    energy  ...               221        222         223
track_id                                        ...                                         
2              0.416675     0.675894  0.634476  ...           3.61288  13.316690  262.929749
3              0.374408     0.528643  0.817461  ...           6.01864  16.673548  325.581085
5              0.043567     0.745566  0.701470  ...           5.86635  16.013849  356.755737
10             0.951670     0.658179  0.924525  ...           8.33319  21.317064  483.403809
134            0.452217     0.513238  0.560410  ...          11.20267  26.454180  751.147705

[5 rows x 249 columns]

In [100]:
# Display the top portion of each sub section of the echonest data

ipd.display(echonest['echonest', 'audio_features'].head())
ipd.display(echonest['echonest', 'metadata'].head())
ipd.display(echonest['echonest', 'ranks'].head())
ipd.display(echonest['echonest', 'social_features'].head())
ipd.display(echonest['echonest', 'temporal_features'].head())


acousticness  danceability    energy  ...  speechiness    tempo   valence
track_id                                        ...                                
2             0.416675      0.675894  0.634476  ...     0.159310  165.922  0.576661
3             0.374408      0.528643  0.817461  ...     0.461818  126.957  0.269240
5             0.043567      0.745566  0.701470  ...     0.124595  100.260  0.621661
10            0.951670      0.658179  0.924525  ...     0.032985  111.562  0.963590
134           0.452217      0.513238  0.560410  ...     0.525519  114.290  0.894072

[5 rows x 8 columns]

album_date         album_name  ...  artist_name               release
track_id                                 ...                                   
2                NaN                NaN  ...         AWOL  AWOL - A Way Of Life
3                NaN                NaN  ...         AWOL  AWOL - A Way Of Life
5                NaN                NaN  ...         AWOL  AWOL - A Way Of Life
10        2008-03-11  Constant Hitmaker  ...    Kurt Vile     Constant Hitmaker
134              NaN                NaN  ...         AWOL  AWOL - A Way Of Life

[5 rows x 7 columns]

artist_discovery_rank  ...  song_hotttnesss_rank
track_id                         ...                      
2                           NaN  ...                   NaN
3                           NaN  ...                   NaN
5                           NaN  ...                   NaN
10                       2635.0  ...               67609.0
134                         NaN  ...                   NaN

[5 rows x 5 columns]

artist_discovery  artist_familiarity  ...  song_currency  song_hotttnesss
track_id                                        ...                                
2                 0.388990            0.386740  ...       0.000000         0.000000
3                 0.388990            0.386740  ...       0.000000         0.000000
5                 0.388990            0.386740  ...       0.000000         0.000000
10                0.557339            0.614272  ...       0.005158         0.354516
134               0.388990            0.386740  ...       0.000000         0.000000

[5 rows x 5 columns]

000       001       002  ...       221        222         223
track_id                                ...                                 
2         0.877233  0.588911  0.354243  ...   3.61288  13.316690  262.929749
3         0.534429  0.537414  0.443299  ...   6.01864  16.673548  325.581085
5         0.548093  0.720192  0.389257  ...   5.86635  16.013849  356.755737
10        0.311404  0.711402  0.321914  ...   8.33319  21.317064  483.403809
134       0.610849  0.569169  0.428494  ...  11.20267  26.454180  751.147705

[5 rows x 224 columns]

##### **2.4 - The Features Dataset**

"Features data contains per track common features extracted with librosa, for all 106,574 tracks"

The header of this CSV is a little bit more complicated in structure than the others, with the index column having multiple levels.

For details on what each column header for this dataset means, consult the [`Librosa package documentation`](https://librosa.org/doc/main/index.html "Librosa documentation")

It is seen that the features dataset is comprised of music statistical information [`(see MIR documentatoin)`](https://musicinformationretrieval.com/index.html "more info") computed using the Librosa package. Some highlights in this dataset for understanding the characteristics of the music files are:
- *rmse:* this represents the root-mean-square-energy (rmse) of each audio track. "For audio signals, that roughly corresponds to how loud the signal is" [`more information on rmse here`](https://musicinformationretrieval.com/energy.html "RMSE")
- *zcr:* this represents zero-crossing-rate (zcr). "The zero crossing rate indicates the number of times that a signal crosses the horizontal axis". This can be though of as a measure of music complexity - how conjunct or disjunct the music is. [`more information on zcr here`](https://musicinformationretrieval.com/zcr.html "ZCR")

In [109]:
features.head()

feature    chroma_cens                      ...       zcr                    
statistics    kurtosis                      ...       min      skew       std
number              01        02        03  ...        01        01        01
track_id                                    ...                              
2             7.180653  5.230309  0.249321  ...  0.000000  2.089872  0.061448
3             1.888963  0.760539  0.345297  ...  0.000000  1.716724  0.069330
5             0.527563 -0.077654 -0.279610  ...  0.000000  2.193303  0.044861
10            3.702245 -0.291193  2.196742  ...  0.000000  3.542325  0.040800
20           -0.193837 -0.198527  0.201546  ...  0.000977  3.189831  0.030993

[5 rows x 518 columns]

In [110]:
# Display the top portion of each sub section of the echonest data

columns = ['mfcc', 'chroma_cens', 'tonnetz', 'spectral_contrast']
columns.append(['spectral_centroid', 'spectral_bandwidth', 'spectral_rolloff'])
columns.append(['rmse', 'zcr'])
for column in columns:
    ipd.display(features[column].head().style.format('{:.2f}'))